### ISSUE TITLE
Theme cannot be switched by clicking on the preview image

### ISSUE THREAD

**Issue by isantop** [pop-os/theme-switcher#2]
I would expect the theme switcher to allow clicking on the preview images for each theme to change the theme, however, this is not the case. The only thing that can be clicked is the (small) radio button under each option.

**Comment by brs17** [comment]
Related, when selecting the image itself, it creates an odd selection around the "Light" or "Dark" option.

![theme-switcher](https://user-images.githubusercontent.com/7460774/66927426-06177900-efed-11e9-9681-2a0fcbfca7d2.png)

**Comment by mmstick** [comment]
This will be fixed the next time I update dependencies for the project.

**Comment by mmstick** [comment]
The last commit was amended to make this package to build again. The selectors will appear if you use a keyboard to select the option, though.

**Comment by isantop** [comment]
I don't think we want to make the focus border go away; that's an important accessibility feature. However, the widget should not expand so much so that the border is more appropriately sized.

**Comment by mmstick** [comment]
That's what's been done. There's still a selection border when using the keyboard, but the switcher is now start-aligned.

**Comment by jackpot51** [comment]
I can confirm that this is fixed
