### ISSUE TITLE
Bad looking outline around the chosen mode extends well below the option.

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/theme-switcher#7]
![Screenshot from 2019-10-17 12-07-53](https://user-images.githubusercontent.com/3430283/67035516-08560200-f0d7-11e9-8343-868adbaee738.png)

**Comment by mmstick** [comment]
Fixed in https://github.com/pop-os/gnome-control-center/commit/cea81e46d880c687275be89bd1eed6399dd8e68a

**Comment by isantop** [comment]
Can confirm this is fixed, I'm going to close this to clean up the TODO list
