### ISSUE TITLE
Solarized Theme Addition Suggestion

### ISSUE THREAD

**Issue by cyberpika2** [pop-os/theme-switcher#8]
Please include Solarized Dark/Light theme. I think it meshes well with the target audience of developers.
Especially if you had a time of day swap.

This is a good implementation in gnome that includes icons, cursors, and theme:
`
https://github.com/rtlewis88/rtl88-Themes/tree/Solarized-Dark
`
`
https://github.com/rtlewis88/rtl88-Themes/tree/Solarized-Light
`

Thank you!

**Comment by isantop** [comment]
The colors in the Solarized have a tendency to clash with the colors in the Pop theme, and one goal of the design is to reduce blue-light emission in dark environments, which makes Solarized-Dark somewhat of a non-starter. The Pop theme is being developed with similar goals to the Solarized themes with aesthetics that better match our branding and design for the default options.

If you prefer the Solarized themes, I suggest installing those on Pop_OS to get the setup you prefer.
